### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rgagnon** [timscott/react-devise#1]
Hi, 

We are willing to try your lib, can you tell me a bit more about the setup if you want?

is it with devise_auth_token gem?

Thank you in advance

**Comment by timscott** [comment]
Wow, that was fast. This module is strictly experimental at this point. I am starting a new app that I plan to use this in, but I'm just getting started.

That said, I whipped together some docs in the README. Hopefully they will make some sense. Please let me know your feedback as you try it out!

**Comment by rgagnon** [comment]
Great thank you.  

I'm on it this morning.

keep you in touch

**Comment by timscott** [comment]
I had left out some important steps in the Rails setup docs which I have added this morning. You might want to take another look. Specifically, I left out setting up ```devise-jwt```. Also I adding something to the devise initializer.

I also added one small feature: the ability to customize the default view plugin in the config settings.

**Comment by rgagnon** [comment]
OK got it.  I'll change for 'devise-jwt'

Do you know why I can see the sign_in and sign_up form but I can't type anything in the input fields?

**Comment by timscott** [comment]
Hmm, no. Are you using any plugin or just taking the default? That should be a simple HTML input.

**Comment by rgagnon** [comment]
Yes I'm using the default, anyway I'll figure it out.

thanks
