### ISSUE TITLE
FYI, latest version is different from the Reference App

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#12]
Likely intentional? But for anyone else running into issues, FYI, the latest version of react-devise `0.0.15` is different than the reference app which is using "react-devise": "^0.0.6",

**Comment by timscott** [comment]
True, have not updated in a while. I'll close this issue, but if to open an issue in the demo repo, I'll leave that open as a placeholder. Of course PRs accepted.

**Comment by timscott** [comment]
True, have not updated in a while. I'll close this issue, but if to open an issue in the demo repo, I'll leave that open as a placeholder. Of course PRs accepted.

**Comment by timscott** [comment]
I have updated the sample.
