### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by renannobile** [timscott/react-devise#14]
Hey there,

Is there i18n support? If not, will there ever be?

Thanks

**Comment by timscott** [comment]
There is no built-in i18n support. I'm not currently using this library, so it's unlikely I would add that anytime soon. However, I'm happy for contributions.

In the meantime, you could achieve localization with [custom messages](https://github.com/timscott/react-devise/wiki/Customization-Basics#configuration) and [custom views](https://github.com/timscott/react-devise/wiki/Customizing-Views#custom-views).

**Comment by renannobile** [comment]
I see, thank you for the feedback.
