### ISSUE TITLE
Device Form Inputs are Disabled?

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#3]
First off, thank you for creating React Devise - I've been looking for something exactly like this!!!

I just added react-devise to my React app. I'm now able to load/see the react-devise views like: http://localhost:8080/users/login

What's happening now, is while I see the form fields, can focus in on the fields, I can't actually type or paste any values into the input field. Was there a step I missed on how to enable the ability to input in the form fields?

Thanks

**Comment by timscott** [comment]
@bhellman1 - I'm not sure what might cause that. I just published a sample app as a reference implementation. You might pull down that code and see if you can reproduce the problem in the sample app.

https://github.com/timscott/react-devise-sample

**Comment by bhellman1** [comment]
This is incredibly helpful and appreciated. **Thank you!**
