### ISSUE TITLE
PrivateRoute params support

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#6]
Hi Tim, while working with react-devise, I was trying to use a param in <PrivateRoute /> but the child component was not able to receive the param.  Example:

`<PrivateRoute path="/welcome/:number" layout={MainLayout} component={Welcome} />`

By changing the above to:` <Route path="/welcome/:number" layout={MainLayout} component={Welcome} />`

The child component started to receive the param as expected. Was this intentional with 
`<PrivateRoute>`? Is it possible to have `<PrivateRoute>` support url params? Thanks!

**Comment by timscott** [comment]
I don't understand the question. It looks like you tried to provide an example, but didn't. This module should not affect access to URL params.

**Comment by bhellman1** [comment]
sorry about that, updated the comment with the correct code formatting so the example appears.

**Comment by timscott** [comment]
Fixed in v0.0.8.
