### ISSUE TITLE
Customizing the SignUpForm

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#7]
Hello, I'm looking to customize the SignUpForm as follows:

- 1. Password field - only require one password entry field
- 2. FirstName, LastName fields to populate user.fname, and user.lname

Is this currently supported with react-devise?

**Comment by bhellman1** [comment]
fyi, here's what I tried:

in setup.js:
```
...
import SignUpForm2 from '../components/users/SignUpForm';
....
const getReactDeviseConfig = initReactDevise({
  viewPlugins: [
    {
      ....
      SignUpForm: SignUpForm2,
    }
  ],
  messages: {
    loginFailed: 'Whoa there. Bad login!'
  }
});
```

And then components/users/SignUpForm:
```

import React from 'react';
import {connect} from 'react-redux';
import {reduxForm, Field} from 'redux-form';
import {Redirect} from 'react-router-dom';
import {signUp, formAction} from 'react-devise';


const SignUpForm2 = reduxForm({
  form: 'signUp'
})(({error, submitting, submitSucceeded, handleSubmit, onSubmit, auth: {messages: {signUpSucceeded: signUpSucceededMessage}, viewPlugin: {renderInput, SubmitButton, Form, FormError}}}) => {
  if (submitSucceeded) {
    return <Redirect to={{
      pathname: '/',
      state: {
        notice: signUpSucceededMessage
      }}}
    />;
  }
  return (
    <Form onSubmit={handleSubmit(formAction(onSubmit))}>

      <Field
        name="fname"
        component={renderInput}
        label="fname"
      />


      <Field
        name="lname"
        component={renderInput}
        label="lname"
      />

      <Field
        name="email"
        component={renderInput}
        label="Email"
      />
      <Field
        name="password"
        type="password"
        component={renderInput}
        label="Password"
      />
      <SubmitButton
        label={submitting ? 'Signing Up...' : 'Sign Up'}
        disabled={submitting}
      />
      {error && <FormError>{error}</FormError>}
    </Form>
  );
});

export default SignUpForm2;

```

**Comment by timscott** [comment]
Until now, it was not possible. However, I have just pushed v0.0.10, which lets you customize routes like so:

```js
initReactDevise({
  // other config
  routes: {
    signup: {
      component: SignUpForm2,
      path: '/you/can/change/the/path',
      linkText: 'You Can Change The Link Text Too... Hey, Signup!'
    }
  }
});
```

The value of `routes` will be deep-merged with the [defaultRoutes](https://github.com/timscott/react-devise/blob/master/src/config/defaultRoutes.js).

Similar to server-rendered Devise, you can create a custom view by copying an modifying the built-in view. It appears you have done that already.

You probably know you will have to do some customization on the server (unrelated to `react-devise`). It's explained here: http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html

NOTE: ViewPlugins are hooks to customize how the built-in views are rendered, not to swap out the view.

**Comment by bhellman1** [comment]
This is great. Thank you! 

fyi, I was able to get it to work w:

```
  routes: {
    signup: {
      component: SignUp
    }
  }
```

If I tried to set `path`, with any type of URL it would not work. The browser would load an empty white page, no errors.

**Comment by timscott** [comment]
The path is relative to the value of clientResourceName, which defaults to 'users'.

So in my example the full path would be `/users/you/can/change/the/path`.
