### ISSUE TITLE
Is there a way to get Auth information within App.jsx? 

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise#9]
I'm looking to learn if the user is authenticated for routing purposes within App.jsx, something like:

```
const isLoggedIn = () => {
  console.log('FIGURE IT OUT HERE');
  return true;
};
const App = ({store}) => {

  return (
    <StyledComponentsThemeProvider theme={theme}>
      <MuiThemeProvider muiTheme={getMuiTheme(theme)} store={store}>
          <StoreProvider store={store}>
            <ConnectedRouter history={history}>
              <Switch>
                  ....
                <WithMainLayout exact path="/" component={Home} render={() => (
                  isLoggedIn() ? (
                  <Redirect to="/dashboard" />
                  ) : (
                  <WithMainLayout component={Home} />
                  )
                )}/>
```

The idea with the above is to allow the app to know where `/` should take the user. Is this supported out of the box with react-devise? Thanks

**Comment by timscott** [comment]
Connect it to your container, like here: https://github.com/timscott/react-devise-sample/blob/c6246302509a2612a07d0d2919474d127d794ceb/client/src/home/Home.jsx. Then `currentUser.isLoggedIn`.

**Comment by bhellman1** [comment]
Thanks for the speedy reply. I tried that and got 

`Uncaught Error: Could not find "store" in either the context or props of "Connect(Authorized)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Authorized)".`

Perhaps I'm doing it wrong.

App.jsx
```
....
import {connect} from 'react-redux';
import {withAuth} from 'react-devise';

const isLoggedIn = (currentUser) => {
  console.log('FIGURE IT OUT HERE');
  console.log(currentUser)
  return true;
};

const App = ({store, currentUser}) => {
....
                <WithMainLayout exact path="/" component={Home} render={() => (
                  isLoggedIn(currentUser) ? (
                  <Redirect to="/dashboard" />
                  ) : (
                  <WithMainLayout component={Home} />
                  )
                )}/>
....

const mapStateToProps = state => {
  return {
    currentUser: state.currentUser
  };
};

export default connect(mapStateToProps)(withAuth(AppProvider));
```

**Comment by timscott** [comment]
I'm not seeing where `AppProvider` is coming from. It sounds like you're trying to `connect` a component outside `App`. You cannot do that since your store would not be available. It seems you want to check inside `WithMainLayout`. 

It probably makes more sense to connect `Home` and do your redirect there. Or even in the main layout.

**Comment by bhellman1** [comment]
Good call re: handling in Home, that ended up being a lot cleaner. Thanks!
